### PR TITLE
Constraints overhaul.

### PR DESCRIPTION
**Pull request by SpacemanPaul**
* Switch to post odc-stats split code of all packages, from official
    PyPI releases.
  * Magic version of hdstats now the only thing coming from dea PyPI.
  * aiobotocore to 2.0.0
  * odc-stats version to 1.0.7  (NB won't work until after https://github.com/opendatacube/odc-stats/pull/8  merges)

### CODE REVIEW

**Review by supermarkion — APPROVED** [review]
LGTM

**Comment by SpacemanPaul** [comment]
Waiting for confirmation tests from Nikita.

**Review by NikitaGandhi — APPROVED** [review]
Thanks @SpacemanPaul. I can confirm `gm_s2` plugin works with `odc-stats==1.0.7`

**Comment by alexgleith** [comment]
This is merged, so just a comment, but using `pip-compile` to create the constraints file seems to be the best way to do it, from my experience.

**Comment by SpacemanPaul** [comment]
Yeah, I'm using pip-compile for the docker image in odc-stats that hosts github testing, and after that journey in the bowels of dependency hell, I'm pretty keen to merge these two odc-stats docker images into one.

**Pull request merged**
