### PR TITLE
Add back the odc-apps-cloud since stats K8 workload depends on it.

### PR DESCRIPTION
**Pull request by tebadi**
Include odc-apps-cloud in the stats image since stats K8 job depends on it (to run s3-find).

### CODE REVIEW

**Review by omad — APPROVED** [review]
Not sure why these were removed, but looks good to me!

**Review by omad — CHANGES_REQUESTED** [review]
I think you need to bump the number in `version.txt` to have the new image pushed anywhere though.
Not 100% sure...

**Comment by tebadi** [comment]
> I think you need to bump the number in `version.txt` to have the new image pushed anywhere though. Not 100% sure...

Yes, You're right.  I bumped it up.

**Review by omad — APPROVED** [review]
:fireworks:

**Pull request merged**
