### PR TITLE
Update dependencies and bump version

### PR DESCRIPTION
**Pull request by pjonsson**

### CODE REVIEW

**Comment by pjonsson** [comment]
@alexgleith apparently we suddenly fail on eodatasets3 using distutils, which you fixed in eodatasets3 a couple of weeks ago. This is despite the eodatasets3 version remaining the same across updates. I feel Python 3.12 support should be pretty important by now, can you make a eodatasets3 release?

**Comment by alexgleith** [comment]
Hey @pjonsson, I did fix this issue, but I'll need @Ariana-B to do a release of eo-datasets. Can we do that please Ariana?

**Comment by Ariana-B** [comment]
Apologies for the delay - the latest version of eo-datasets has now been released @pjonsson @alexgleith

**Comment by alexgleith** [comment]
Awesome, thanks @Ariana-B!

**Comment by pjonsson** [comment]
@Ariana-B thank you for the quick release!

@alexgleith I've used Ruff for almost a year by now and it's amazing, so I like your suggestion about using uv for the split image. Unfortunately I need to punt that work for later, so it would be nice to get this merged now so we get a GDAL 3.10.0-based release.

**Review by alexgleith — APPROVED** [review]

**Pull request merged**
